# Data Exploration 
By Brandon Khuu
Last update: 5/4/2021
### Goal
Removal of outlier data points from the dataset

In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Import data
df = pd.read_csv('Organoid Files/all_autism_fpkm_t_threshold.csv', header=0, index_col=0)
print(df.head())

           Autism  CDK5RAP1    TMEM246       PKD1     EDEM1      LSM11  \
PGP1-1          0  5.561823   9.167399   4.762467  4.259699   3.333153
PGP1-2          0  2.050032   6.121957   3.086031  3.888580   3.064389
PGP1-3          0  2.481599  14.205795   8.663784  2.988719  13.747564
GM23716-1       0  4.396121  15.263531   8.198981  3.433083  13.873706
GM23716-2       0  3.721746  14.125613  10.278191  3.331196  13.211928

            COL26A1      CPSF6      DCTN5     MRPS33  ...      UBE2T  \
PGP1-1     5.245319  15.288924  10.670947  15.418737  ...  36.320081
PGP1-2     4.530108  14.225061  11.109630  21.596005  ...  19.707959
PGP1-3     6.189141  18.021990  15.850792   9.871680  ...  15.002978
GM23716-1  5.018456  17.714552  15.832140   4.594193  ...  13.609106
GM23716-2  5.620373  15.806883  15.434513   7.544800  ...  13.346974

                PTK7    EIF2B3      CDK16  C15orf61       GSTP1       IPP  \
PGP1-1     23.422699  6.506580   7.639236  1.808342  253.147425  2.624415
PGP1-2     12.679506  6.687741   7.457054  1.614225  290.182382  3.276070
PGP1-3      9.314311  6.744241  36.158595  3.626686  118.126815  2.221963
GM23716-1   9.826147  6.570986  32.786094  3.988325  103.634970  2.459700
GM23716-2   4.147004  5.990253  55.245293  3.849378  111.978695  2.494851

               ASB3      EHD4      NRSN2
PGP1-1     5.473228  9.892221  14.017985
PGP1-2     7.483068  7.377414  11.613564
PGP1-3     5.087976  2.392554  15.666102
GM23716-1  4.626596  2.301205  16.500382
GM23716-2  4.843815  2.285043  18.534124

[5 rows x 11272 columns]

In [3]:
#transpose data
df_t = df.T
df_t2 = df_t.drop("Autism",axis=0)
print(df_t.head())

            PGP1-1    PGP1-2     PGP1-3  GM23716-1  GM23716-2  GM23716-3  \
Autism    0.000000  0.000000   0.000000   0.000000   0.000000   0.000000
CDK5RAP1  5.561823  2.050032   2.481599   4.396121   3.721746   2.260565
TMEM246   9.167399  6.121957  14.205795  15.263531  14.125613   6.008471
PKD1      4.762467  3.086031   8.663784   8.198981  10.278191   5.577455
EDEM1     4.259699  3.888580   2.988719   3.433083   3.331196   3.524835

          GM23720-1  GM23720-2  GM23720-3  GM25256-1  ...  14739x3-2  \
Autism     0.000000   0.000000   0.000000   0.000000  ...   1.000000
CDK5RAP1   3.482430   3.136405   4.645353   1.642499  ...   6.594048
TMEM246    5.544019   5.302956   7.467318   8.261944  ...   3.478945
PKD1       4.226272   4.628730   7.837992   4.989404  ...   8.564923
EDEM1      3.539229   3.586650   3.683216   2.584456  ...   5.435888

          14765x2-1  14765x2-2  14765x2-3  14710x6-1  14781x16-1  14781x16-2  \
Autism     1.000000   1.000000   1.000000   1.000000    1.000000    1.000000
CDK5RAP1   6.941136   7.453001   3.405732   2.784555    6.384259    3.128289
TMEM246    4.855474   4.652040   7.574598   6.334495    7.771520    8.186893
PKD1       6.328464   3.316495  16.091198   9.193670    7.071175    9.025883
EDEM1      6.711067   5.737995   2.197396   2.511982    3.297171    4.009783

          14781x16-3  14746x8-1  14746x8-2
Autism      1.000000   1.000000   1.000000
CDK5RAP1    7.880060   3.388043   3.623195
TMEM246     4.857521   3.334954   6.834265
PKD1        7.076191  10.996357   3.154569
EDEM1       4.097137   1.545692   3.818004

[5 rows x 71 columns]

In [4]:
#brief summary of data
df_t_summary = df_t2.describe()
df_t_summary

,PGP1-1,PGP1-2,PGP1-3,GM23716-1,GM23716-2,GM23716-3,GM23720-1,GM23720-2,GM23720-3,GM25256-1,...,14739x3-2,14765x2-1,14765x2-2,14765x2-3,14710x6-1,14781x16-1,14781x16-2,14781x16-3,14746x8-1,14746x8-2
count,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,...,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000,11271.000000
mean,45.493531,42.625457,39.555400,35.248826,39.052916,42.433180,40.952593,41.859084,32.960577,34.865044,...,49.760616,46.249395,56.914139,49.636772,37.670128,35.479490,34.272116,34.836925,65.872056,41.842926
std,742.675941,715.747308,600.088567,508.154653,570.805906,673.079865,621.930712,668.549659,469.548056,540.059589,...,608.868040,544.334981,931.189080,928.624351,541.850393,465.657382,490.620253,455.765364,1486.193192,673.340243
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.722227,3.734914,3.169003,3.111226,3.188661,3.508799,3.481028,3.553223,3.184222,2.691323,...,4.144012,4.252948,3.906816,2.838371,2.332892,3.232181,3.099344,3.848319,1.739788,3.831544
50%,6.936604,6.851779,6.399141,6.256436,6.452555,6.608453,6.442106,6.760292,5.599489,5.115518,...,7.735507,7.921045,7.321876,5.635765,4.593434,6.358012,6.030680,7.084209,3.746284,6.935098
75%,14.440164,13.800521,13.560017,13.004138,13.179339,13.512505,12.949509,13.911387,11.115301,11.043108,...,16.771967,16.536188,15.498181,13.185448,9.768343,13.147192,12.162489,14.020563,9.552623,14.078767
max,53648.599060,53720.015420,44799.838590,37983.603830,44144.970880,52093.885530,47218.597180,47635.006370,30772.426570,40298.902400,...,43435.423380,41118.439940,74709.848710,75167.285210,30276.174060,31586.538790,36767.365050,33985.802690,102370.845800,47980.794720

In [5]:
#create IQR
iqr = (df_t_summary.loc['75%'] - df_t_summary.loc['25%'])
iqr = iqr*1.5
top_bound = df_t_summary.loc['75%'] + iqr
top_bound

PGP1-1        30.517071
PGP1-2        28.898931
PGP1-3        29.146537
GM23716-1     27.843505
GM23716-2     28.165358
                ...
14781x16-1    28.019709
14781x16-2    25.757206
14781x16-3    29.278929
14746x8-1     21.271875
14746x8-2     29.449602
Length: 71, dtype: float64

In [6]:
#Apply IQR*1.5 filter
lst = [i for i in df_t2.columns]
index = df_t2.index

drop_list = []
for i in lst:
    temp = df_t2.get(i)
    for j in range(temp.shape[0]):
        if temp[j] > top_bound[i]:
            drop_list.append(j)

In [7]:
#drop cols that don't meet filter requriments
drop_list.sort()
drop_set = set(drop_list)
col_to_drop =[index[i] for i in drop_set]

In [8]:
df_t = df_t.drop(index=col_to_drop)
df_t

,PGP1-1,PGP1-2,PGP1-3,GM23716-1,GM23716-2,GM23716-3,GM23720-1,GM23720-2,GM23720-3,GM25256-1,...,14739x3-2,14765x2-1,14765x2-2,14765x2-3,14710x6-1,14781x16-1,14781x16-2,14781x16-3,14746x8-1,14746x8-2
Autism,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
CDK5RAP1,5.561823,2.050032,2.481599,4.396121,3.721746,2.260565,3.482430,3.136405,4.645353,1.642499,...,6.594048,6.941136,7.453001,3.405732,2.784555,6.384259,3.128289,7.880060,3.388043,3.623195
TMEM246,9.167399,6.121957,14.205795,15.263531,14.125613,6.008471,5.544019,5.302956,7.467318,8.261944,...,3.478945,4.855474,4.652040,7.574598,6.334495,7.771520,8.186893,4.857521,3.334954,6.834265
PKD1,4.762467,3.086031,8.663784,8.198981,10.278191,5.577455,4.226272,4.628730,7.837992,4.989404,...,8.564923,6.328464,3.316495,16.091198,9.193670,7.071175,9.025883,7.076191,10.996357,3.154569
EDEM1,4.259699,3.888580,2.988719,3.433083,3.331196,3.524835,3.539229,3.586650,3.683216,2.584456,...,5.435888,6.711067,5.737995,2.197396,2.511982,3.297171,4.009783,4.097137,1.545692,3.818004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C15orf61,1.808342,1.614225,3.626686,3.988325,3.849378,2.492051,2.444973,2.693613,1.986357,2.075116,...,3.700545,2.444722,2.217770,3.151912,2.380416,2.247722,2.320908,2.000993,2.186490,2.133355
IPP,2.624415,3.276070,2.221963,2.459700,2.494851,2.709586,3.061299,2.624201,1.968269,1.557976,...,3.051684,3.494056,2.581620,1.781817,1.212175,1.998373,2.860871,3.957021,1.027271,2.857793
ASB3,5.473228,7.483068,5.087976,4.626596,4.843815,4.070593,5.959431,6.158053,3.544103,3.774926,...,4.541933,5.249603,3.367538,1.850787,3.337475,4.476631,2.771161,5.646545,1.624070,6.195983
EHD4,9.892221,7.377414,2.392554,2.301205,2.285043,6.619956,5.504483,7.258999,3.836467,3.230283,...,9.353551,9.585201,8.558917,6.019472,1.798324,2.150457,2.254990,2.751370,2.718903,8.082016
NRSN2,14.017985,11.613564,15.666102,16.500382,18.534124,10.859041,9.576354,10.262843,12.230454,14.408656,...,16.484673,13.321338,12.395962,22.703151,12.912054,14.543974,10.858082,12.931406,17.184158,11.506148

In [9]:
df2 = df_t.T
df2

,Autism,CDK5RAP1,TMEM246,PKD1,EDEM1,LSM11,COL26A1,CPSF6,DCTN5,TIMM9,...,NHLRC3,CCDC130,PIK3C3,PRKAB2,EIF2B3,C15orf61,IPP,ASB3,EHD4,NRSN2
PGP1-1,0.0,5.561823,9.167399,4.762467,4.259699,3.333153,5.245319,15.288924,10.670947,12.501312,...,3.577807,10.246243,9.379072,7.974797,6.506580,1.808342,2.624415,5.473228,9.892221,14.017985
PGP1-2,0.0,2.050032,6.121957,3.086031,3.888580,3.064389,4.530108,14.225061,11.109630,14.227982,...,2.951153,8.455335,13.197261,7.847511,6.687741,1.614225,3.276070,7.483068,7.377414,11.613564
PGP1-3,0.0,2.481599,14.205795,8.663784,2.988719,13.747564,6.189141,18.021990,15.850792,9.134396,...,3.211442,9.928194,7.313368,9.023667,6.744241,3.626686,2.221963,5.087976,2.392554,15.666102
GM23716-1,0.0,4.396121,15.263531,8.198981,3.433083,13.873706,5.018456,17.714552,15.832140,8.492397,...,3.052629,9.895930,7.927309,9.817574,6.570986,3.988325,2.459700,4.626596,2.301205,16.500382
GM23716-2,0.0,3.721746,14.125613,10.278191,3.331196,13.211928,5.620373,15.806883,15.434513,8.410669,...,2.743381,9.354041,8.525394,8.338526,5.990253,3.849378,2.494851,4.843815,2.285043,18.534124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14781x16-1,1.0,6.384259,7.771520,7.071175,3.297171,5.224131,4.838935,16.391965,13.168677,10.776919,...,1.637049,12.027670,11.101225,10.772747,8.583395,2.247722,1.998373,4.476631,2.150457,14.543974
14781x16-2,1.0,3.128289,8.186893,9.025883,4.009783,4.728078,6.729686,13.232519,10.730565,12.409964,...,2.305655,11.762725,8.595687,9.600968,6.306627,2.320908,2.860871,2.771161,2.254990,10.858082
14781x16-3,1.0,7.880060,4.857521,7.076191,4.097137,5.166222,5.299588,21.528132,11.529954,13.209200,...,3.237814,11.756826,12.915368,10.664276,6.284167,2.000993,3.957021,5.646545,2.751370,12.931406
14746x8-1,1.0,3.388043,3.334954,10.996357,1.545692,1.109277,6.404090,4.283906,2.709484,6.715611,...,1.075425,11.878050,2.495181,2.330291,2.285754,2.186490,1.027271,1.624070,2.718903,17.184158
14746x8-2,1.0,3.623195,6.834265,3.154569,3.818004,3.262106,4.399106,15.213019,10.777413,12.144656,...,3.348133,8.902245,11.416633,7.656260,5.690446,2.133355,2.857793,6.195983,8.082016,11.506148

In [25]:
#import DNA data

csv_lst = ['VCFs/chrm_split/chr1.csv', 'VCFs/chrm_split/chr2.csv','VCFs/chrm_split/chr3.csv','VCFs/chrm_split/chr4.csv','VCFs/chrm_split/chr5.csv',
'VCFs/chrm_split/chr6.csv','VCFs/chrm_split/chr7.csv','VCFs/chrm_split/chr8.csv','VCFs/chrm_split/chr9.csv','VCFs/chrm_split/chr10.csv',
'VCFs/chrm_split/chr11.csv','VCFs/chrm_split/chr12.csv','VCFs/chrm_split/chr13.csv','VCFs/chrm_split/chr14.csv','VCFs/chrm_split/chr15.csv',
'VCFs/chrm_split/chr16.csv','VCFs/chrm_split/chr17.csv','VCFs/chrm_split/chr18.csv','VCFs/chrm_split/chr19.csv','VCFs/chrm_split/chr20.csv',
'VCFs/chrm_split/chr21.csv','VCFs/chrm_split/chr22.csv','VCFs/chrm_split/chrX.csv','VCFs/chrm_split/chrY.csv']

def storage_lst(file_lst):
    lst = []
    for i in file_lst:
        df = pd.read_csv(i, header=0)
        df = df.drop('Unnamed: 0', axis=1)
        lst.append(df)  
    return lst

df_list = storage_lst(csv_lst)

In [26]:
#merge dna data
dna = pd.concat(df_list,ignore_index=True)
dna.head()

,CHROM,POS,14765x2,14763x7,14799x1,14858x3,14746x8,14824x13,14739x13,14710x6,...,BXS0111,BYS0112,BXS0114,BXS0115,BXS0116,BXS0117,GM23716,GM23720,GM25256,PGP1
0,chr1,69511,Homozygous Alternate,Homozygous Reference,Homozygous Alternate,Homozygous Alternate,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Alternate,...,Homozygous Alternate,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate
1,chr1,762273,Heterozygous Alternate,Homozygous Alternate,Heterozygous Alternate,Homozygous Alternate,Homozygous Alternate,Heterozygous Alternate,Homozygous Alternate,Homozygous Reference,...,Heterozygous Alternate,Homozygous Alternate,Heterozygous Alternate,Homozygous Reference,Heterozygous Alternate,Homozygous Alternate,Homozygous Reference,Homozygous Alternate,Heterozygous Alternate,Heterozygous Alternate
2,chr1,782981,Heterozygous Alternate,Homozygous Reference,Heterozygous Alternate,Homozygous Reference,Homozygous Reference,Heterozygous Alternate,Homozygous Reference,Homozygous Alternate,...,Homozygous Reference,Homozygous Reference,Heterozygous Alternate,Homozygous Alternate,Heterozygous Alternate,Heterozygous Alternate,Heterozygous Alternate,Homozygous Reference,Heterozygous Alternate,Heterozygous Alternate
3,chr1,792263,Heterozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Heterozygous Alternate,Homozygous Alternate,Heterozygous Alternate,...,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Heterozygous Alternate,Heterozygous Alternate,Heterozygous Alternate,Homozygous Alternate,Homozygous Alternate,Heterozygous Alternate
4,chr1,792480,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,...,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Heterozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate

In [27]:
#create col header for transposed dna dataframe
chrmPos = []
for i in range(dna.shape[0]):
    s = str(dna.CHROM[i]) + '@' + str(dna.POS[i])
    chrmPos.append(s)
    
#append to dataframe and prep for analysis
dna.insert(loc=0, column='Samples', value=chrmPos)
dna = dna.drop(['CHROM','POS'], axis=1)
dna = dna.set_index('Samples')
dna = dna.T
display(dna.head())

Samples,chr1@69511,chr1@762273,chr1@782981,chr1@792263,chr1@792480,chr1@866319,chr1@879676,chr1@879687,chr1@880238,chr1@881627,...,chrY@14107068,chrY@16835007,chrY@15024588,chrY@15021522,chrY@15026658,chrY@21894633,chrY@13309418,chrY@14832620,chrY@5491186,chrY@24457719
14765x2,Homozygous Alternate,Heterozygous Alternate,Heterozygous Alternate,Heterozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Heterozygous Alternate,...,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference
14763x7,Homozygous Reference,Homozygous Alternate,Homozygous Reference,Homozygous Alternate,Homozygous Alternate,Homozygous Reference,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Reference,...,Homozygous Reference,Homozygous Reference,Homozygous Alternate,Homozygous Reference,Homozygous Alternate,Heterozygous Alternate,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference
14799x1,Homozygous Alternate,Heterozygous Alternate,Heterozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Reference,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Reference,...,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Alternate
14858x3,Homozygous Alternate,Homozygous Alternate,Homozygous Reference,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Heterozygous Alternate,...,Homozygous Alternate,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Alternate,Homozygous Reference
14746x8,Homozygous Reference,Homozygous Alternate,Homozygous Reference,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Homozygous Alternate,Heterozygous Alternate,...,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference,Homozygous Reference

In [29]:
#encode data
reference_dict = {'Homozygous Reference':0, 'Heterozygous Alternate':1, 
					'Heterozygous Alternate 2':2,'Homozygous Alternate':3}

dna = dna.replace(reference_dict)
display(dna.head())

Samples,chr1@69511,chr1@762273,chr1@782981,chr1@792263,chr1@792480,chr1@866319,chr1@879676,chr1@879687,chr1@880238,chr1@881627,...,chrY@14107068,chrY@16835007,chrY@15024588,chrY@15021522,chrY@15026658,chrY@21894633,chrY@13309418,chrY@14832620,chrY@5491186,chrY@24457719
14765x2,3,1,1,1,3,3,3,3,3,1,...,0,0,0,0,0,0,0,0,0,0
14763x7,0,3,0,3,3,0,3,3,3,0,...,0,0,3,0,3,1,0,0,0,0
14799x1,3,1,1,3,3,0,3,3,3,0,...,0,0,0,0,0,0,0,0,0,3
14858x3,3,3,0,3,3,3,3,3,3,1,...,3,0,0,0,0,0,0,0,3,0
14746x8,0,3,0,3,3,3,3,3,3,1,...,0,0,0,0,0,0,0,0,0,0

In [30]:
display(dna.describe())

Samples,chr1@69511,chr1@762273,chr1@782981,chr1@792263,chr1@792480,chr1@866319,chr1@879676,chr1@879687,chr1@880238,chr1@881627,...,chrY@14107068,chrY@16835007,chrY@15024588,chrY@15021522,chrY@15026658,chrY@21894633,chrY@13309418,chrY@14832620,chrY@5491186,chrY@24457719
count,25.000000,25.000000,25.000000,25.000000,25.00,25.000000,25.000000,25.000000,25.00000,25.000000,...,25.000000,25.00,25.00,25.000000,25.0000,25.00,25.000000,25.000000,25.000000,25.00
mean,1.680000,1.840000,0.680000,2.240000,2.92,1.840000,1.960000,1.960000,2.52000,1.000000,...,0.560000,0.12,0.12,0.240000,0.1600,0.04,0.240000,0.360000,0.480000,0.12
std,1.519868,1.178983,0.852447,1.051982,0.40,1.462874,1.428286,1.428286,0.87178,1.118034,...,1.121011,0.60,0.60,0.830662,0.6245,0.20,0.830662,0.994987,1.004988,0.60
min,0.000000,0.000000,0.000000,0.000000,1.00,0.000000,0.000000,0.000000,1.00000,0.000000,...,0.000000,0.00,0.00,0.000000,0.0000,0.00,0.000000,0.000000,0.000000,0.00
25%,0.000000,1.000000,0.000000,1.000000,3.00,0.000000,0.000000,0.000000,3.00000,0.000000,...,0.000000,0.00,0.00,0.000000,0.0000,0.00,0.000000,0.000000,0.000000,0.00
50%,3.000000,1.000000,1.000000,3.000000,3.00,3.000000,3.000000,3.000000,3.00000,1.000000,...,0.000000,0.00,0.00,0.000000,0.0000,0.00,0.000000,0.000000,0.000000,0.00
75%,3.000000,3.000000,1.000000,3.000000,3.00,3.000000,3.000000,3.000000,3.00000,1.000000,...,0.000000,0.00,0.00,0.000000,0.0000,0.00,0.000000,0.000000,0.000000,0.00
max,3.000000,3.000000,3.000000,3.000000,3.00,3.000000,3.000000,3.000000,3.00000,3.000000,...,3.000000,3.00,3.00,3.000000,3.0000,1.00,3.000000,3.000000,3.000000,3.00